# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/PWM_FFT/PWM_FFT.srcs/sources_1/ip/clk_16m/clk_16m.xci
# IP: The module: 'clk_16m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/PWM_FFT/PWM_FFT.srcs/sources_1/ip/clk_16m/clk_16m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_16m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/PWM_FFT/PWM_FFT.srcs/sources_1/ip/clk_16m/clk_16m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_16m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/PWM_FFT/PWM_FFT.srcs/sources_1/ip/clk_16m/clk_16m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_16m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/PWM_FFT/PWM_FFT.srcs/sources_1/ip/clk_16m/clk_16m.xci
# IP: The module: 'clk_16m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/PWM_FFT/PWM_FFT.srcs/sources_1/ip/clk_16m/clk_16m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_16m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/PWM_FFT/PWM_FFT.srcs/sources_1/ip/clk_16m/clk_16m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_16m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/PWM_FFT/PWM_FFT.srcs/sources_1/ip/clk_16m/clk_16m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_16m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
