# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/analog_input_FFT/analog_input_FFT.srcs/sources_1/ip/xadc_demo/xadc_demo.xci
# IP: The module: 'xadc_demo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/analog_input_FFT/analog_input_FFT.srcs/sources_1/ip/xadc_demo/xadc_demo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_demo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/analog_input_FFT/analog_input_FFT.srcs/sources_1/ip/xadc_demo/xadc_demo.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_demo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/analog_input_FFT/analog_input_FFT.srcs/sources_1/ip/xadc_demo/xadc_demo.xci
# IP: The module: 'xadc_demo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/analog_input_FFT/analog_input_FFT.srcs/sources_1/ip/xadc_demo/xadc_demo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_demo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/analog_input_FFT/analog_input_FFT.srcs/sources_1/ip/xadc_demo/xadc_demo.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_demo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
