# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/Artix-7-FFT/Artix-7-FFT.srcs/sources_1/ip/bram_frame/bram_frame.xci
# IP: The module: 'bram_frame' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/Artix-7-FFT/Artix-7-FFT.srcs/sources_1/ip/bram_frame/bram_frame_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_frame'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/Artix-7-FFT/Artix-7-FFT.srcs/sources_1/ip/bram_frame/bram_frame.xci
# IP: The module: 'bram_frame' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nick Palladino/Documents/GitHub/digital-logic-project/Artix-7-FFT/Artix-7-FFT.srcs/sources_1/ip/bram_frame/bram_frame_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_frame'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
